package com.timi.model;

public enum Actions {
    CREATE_COURSE,
    DELETE_COURSE,
    UPDATE_COURSE,
    CREATE_QUIZ,
    DELETE_QUIZ,
    UPDATE_QUIZ,
    CREATE_QUESTION,
    DELETE_QUESTION,
    UPDATE_QUESTION,
    CREATE_USER,
    DELETE_USER,
    UPDATE_USER,
    CREATE_ROLE,
    DELETE_ROLE,
    UPDATE_ROLE,
    CREATE_PERMISSION,
    DELETE_PERMISSION,
    UPDATE_PERMISSION,
}
